AllCops:
  TargetRubyVersion: 2.6.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - 'script/*'
    - 'vendor/*'

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 100
